# Setup
title:               "컨벡스 최적화의 모든 것"
tagline:             
description:         ''
url:                 'http://convex-optimization-for-all.github.io'
baseurl:
paginate:            5
permalink:           pretty
# About/contact
author:
  name:              Kyeongmin Woo
  url:               
  email:             wgm0601@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
